In [1]:
import numpy as np
import pandas as pd
import math
from matplotlib import pyplot as plt

In [13]:
death_path = 'pubg-match-deaths/deaths/kill_match_stats_final_0.csv'
agg_path = 'pubg-match-deaths/aggregate/agg_match_stats_0.csv'

pubg_death = pd.read_csv(death_path)
erangel_Map = pubg_death.loc[(pubg_death["map"]=="ERANGEL")]
bad_erangel_match_id = list(erangel_Map.loc[erangel_Map["killed_by"]=="Down and Out", "match_id"].drop_duplicates())
solo_erangel = erangel_Map.loc[~erangel_Map["match_id"].isin(bad_erangel_match_id)]

pubg_agg = pd.read_csv(agg_path)
solo_agg = pubg_agg.loc[~pubg_agg["match_id"].isin(bad_erangel_match_id)]

In [10]:
erangel_ids = []
for _id in solo_agg["match_id"]:
    if _id in solo_erangel["match_id"]:
        erangel_ids.append(_id)
erangel_agg = solo_agg.loc[solo_agg["match_id"].isin(erangel_ids)]
erangel_agg.head()

Empty DataFrame
Columns: [date, game_size, match_id, match_mode, party_size, player_assists, player_dbno, player_dist_ride, player_dist_walk, player_dmg, player_kills, player_name, player_survive_time, team_id, team_placement]
Index: []

In [16]:
solo_agg.head()

,date,game_size,match_id,match_mode,party_size,player_assists,player_dbno,player_dist_ride,player_dist_walk,player_dmg,player_kills,player_name,player_survive_time,team_id,team_placement
402,2018-01-07T03:45:01+0000,47,2U4GBNA0YmnLSqvEycnTjo-KT000vfUnhSA2vfVhVPe1QB...,tpp,2,0,1,391.711945,57.900500,100,0,KCannon98,158.216,6,33
403,2018-01-07T03:45:01+0000,47,2U4GBNA0YmnLSqvEycnTjo-KT000vfUnhSA2vfVhVPe1QB...,tpp,2,0,1,0.000000,364.937622,75,1,X3evolution,193.887,6,33
404,2018-01-07T03:45:01+0000,47,2U4GBNA0YmnLSqvEycnTjo-KT000vfUnhSA2vfVhVPe1QB...,tpp,2,1,0,0.000000,3843.140000,51,0,Kroy2005,1539.123,7,6
405,2018-01-07T03:45:01+0000,47,2U4GBNA0YmnLSqvEycnTjo-KT000vfUnhSA2vfVhVPe1QB...,tpp,2,0,1,0.000000,4047.425540,156,2,IdiotWHJ,1559.906,7,6
406,2018-01-07T03:45:01+0000,47,2U4GBNA0YmnLSqvEycnTjo-KT000vfUnhSA2vfVhVPe1QB...,tpp,2,0,0,0.000000,162.507900,0,0,Thee_Milk_Man,247.826,10,23

In [29]:
wins = solo_agg.loc[solo_agg["team_placement"]==1]
num_wins = len(wins)
num_games = len(solo_agg)
p_win = num_wins/num_games
bayes_columns = ['game_size', 'match_mode', 'party_size', 'player_assists', 'player_dbno',
                 'player_dist_ride', 'player_dist_walk', 'player_dmg', 'player_kills','player_survive_time']
for c in bayes_columns:
    df = solo_agg[c]
    row_set = set(df)
    print(row_set)

{4, 6, 7, 9, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100}
{'tpp'}
{1, 2, 4}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 148, 30, 31, 32, 33, 34, 35, 29, 38, 40}

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)